"""Initial schema

Revision ID: 998e90157435
Revises: 
Create Date: 2026-08-14 00:11:05.668163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# pyrefly: ignore [missing-import]
import pgvector


# revision identifiers, used by Alembic.
revision: str = '998e90157435'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('published_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('article_embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_articles_embedding_hnsw', 'articles', ['article_embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'article_embedding': 'vector_cosine_ops'})
    op.create_table('perspective_pairs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id_a', sa.UUID(), nullable=False),
    sa.Column('article_id_b', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('interest_embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True),
    sa.Column('baseline_political_leaning', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('agent_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('memory_key', sa.String(length=100), nullable=True),
    sa.Column('memory_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('bias_score', sa.Float(), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('source_credibility', sa.Float(), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('read_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading_history')
    op.drop_table('article_metadata')
    op.drop_table('agent_memory')
    op.drop_table('user_profiles')
    op.drop_table('perspective_pairs')
    op.drop_index('ix_articles_embedding_hnsw', table_name='articles', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'article_embedding': 'vector_cosine_ops'})
    op.drop_table('articles')
    # ### end Alembic commands ###
